In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(
    "NIMO_target_list.csv",
    dtype={"gaiadr3_source_id": "string", "TIC": "string"}
)
df.head()

,nimo_id,TIC,gaiadr3_source_id,other_id,group,srmper,# of sectors,Sector 1,Sector 2,Sector 3,...,Sector 92,Sector 93,Sector 94,Sector 95,Sector 96,Sector 97,Sector 98,Sector 99,Sector 100,Sector 101
0,1,350559457,4767439021687332096,2MASS J05461532-5547521,car,Nina,45,SPOC-120,SPOC-120,SPOC-120,...,NaN,FFI-200s,SPOC-120,SPOC-120,FFI-200s,SPOC-120,SPOC-120,NaN,NaN,NaN
1,2,360558208,5838713408461840256,5838713408461840256,epsc,Oliver,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FFI-200s,FFI-200s
2,3,327549481,5855642348500099072,NaN,epsc,Oliver,7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FFI-200s,FFI-200s,FFI-200s
3,4,454335224,5227840175588831744,NaN,epsc,Oliver,6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,410981941,5233403459606590720,NaN,epsc,Oliver,6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df['# of sectors'].sum()

339

In [4]:
mask = df["gaiadr3_source_id"].notna() & df["gaiadr3_source_id"].str.strip().ne("")
df.loc[mask, "# of sectors"].sum()

313

In [5]:
df = df.drop(columns=["other_id", "srmper"])
df.head()

,nimo_id,TIC,gaiadr3_source_id,group,# of sectors,Sector 1,Sector 2,Sector 3,Sector 4,Sector 5,...,Sector 92,Sector 93,Sector 94,Sector 95,Sector 96,Sector 97,Sector 98,Sector 99,Sector 100,Sector 101
0,1,350559457,4767439021687332096,car,45,SPOC-120,SPOC-120,SPOC-120,SPOC-120,SPOC-120,...,NaN,FFI-200s,SPOC-120,SPOC-120,FFI-200s,SPOC-120,SPOC-120,NaN,NaN,NaN
1,2,360558208,5838713408461840256,epsc,7,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FFI-200s,FFI-200s
2,3,327549481,5855642348500099072,epsc,7,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FFI-200s,FFI-200s,FFI-200s
3,4,454335224,5227840175588831744,epsc,6,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,410981941,5233403459606590720,epsc,6,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
id_cols = df.columns[:5].tolist()
sector_cols = [c for c in df.columns if c.startswith("Sector")]

df_rotated = (
    df.melt(
        id_vars=id_cols,
        value_vars=sector_cols,
        var_name="Sector",
        value_name="name"
    )
    .dropna(subset=["name"])
    .loc[lambda x: x["name"].astype(str).str.strip() != ""]
    .copy()
 )

df_rotated["Sector"] = (
    df_rotated["Sector"]
    .str.replace("Sector", "", regex=False)
    .str.strip()
 )

In [7]:
df_rotated[df_rotated.nimo_id==2]

,nimo_id,TIC,gaiadr3_source_id,group,# of sectors,Sector,name
601,2,360558208,5838713408461840256,epsc,7,11,FFI-30min
661,2,360558208,5838713408461840256,epsc,7,12,FFI-30min
2221,2,360558208,5838713408461840256,epsc,7,38,FFI-10min
2281,2,360558208,5838713408461840256,epsc,7,39,FFI-10min
3841,2,360558208,5838713408461840256,epsc,7,65,FFI-200s
5941,2,360558208,5838713408461840256,epsc,7,100,FFI-200s
6001,2,360558208,5838713408461840256,epsc,7,101,FFI-200s

In [8]:
df_rotated["lc_name"] = df_rotated.apply(
    lambda row: f"TIC-{row['TIC']}-{row['Sector']}-{row['name']}", 
    axis=1
)

In [9]:
df_rotated.head(20)

,nimo_id,TIC,gaiadr3_source_id,group,# of sectors,Sector,name,lc_name
0,1,350559457,4767439021687332096,car,45,1,SPOC-120,TIC-350559457-1-SPOC-120
60,1,350559457,4767439021687332096,car,45,2,SPOC-120,TIC-350559457-2-SPOC-120
120,1,350559457,4767439021687332096,car,45,3,SPOC-120,TIC-350559457-3-SPOC-120
180,1,350559457,4767439021687332096,car,45,4,SPOC-120,TIC-350559457-4-SPOC-120
240,1,350559457,4767439021687332096,car,45,5,SPOC-120,TIC-350559457-5-SPOC-120
300,1,350559457,4767439021687332096,car,45,6,SPOC-120,TIC-350559457-6-SPOC-120
309,10,24604498,3209175447332278144,thor,3,6,FFI-30min,TIC-24604498-6-FFI-30min
310,11,158817023,3319628434087776000,thor,3,6,FFI-30min,TIC-158817023-6-FFI-30min
311,12,345772521,32410488806715098,thor,3,6,FFI-30min,TIC-345772521-6-FFI-30min
312,13,311272948,3339253170454118272,thor,4,6,FFI-30min,TIC-311272948-6-FFI-30min
313,14,200001428,3320524914022156288,thor,2,6,FFI-30min,TIC-200001428-6-FFI-30min
314,15,345773622,3238048652740273408,thor,3,6,FFI-30min,TIC-345773622-6-FFI-30min
315,16,389248164,3341538436653898240,thor,7,6,FFI-30min,TIC-389248164-6-FFI-30min
316,17,264461317,3221837251438378624,thor,3,6,FFI-30min,TIC-264461317-6-FFI-30min
317,18,389248318,3341556922194703232,thor,7,6,FFI-30min,TIC-389248318-6-FFI-30min
318,19,365637508,3237973752806799360,thor,3,6,SPOC-120,TIC-365637508-6-SPOC-120
319,20,365692367,3334165249117507968,thor,3,6,FFI-30min,TIC-365692367-6-FFI-30min
320,21,365744968,3337724677494561792,thor,3,6,FFI-30min,TIC-365744968-6-FFI-30min
321,22,365747298,3238063569162793472,thor,3,6,FFI-30min,TIC-365747298-6-FFI-30min
322,23,302417241,<NA>,thor,7,6,FFI-30min,TIC-302417241-6-FFI-30min

In [10]:
df_rotated = df_rotated.rename(columns={'# of sectors': 'num_sectors'})

In [11]:
df_rotated.to_csv('NIMO_lcnames.csv', index=False)

In [12]:
df_rotated[df_rotated['gaiadr3_source_id'].notna()].to_csv('NIMO_gaiaids.csv', index=False)